var db = [
  {
      "dates": [],
      "tags": [],
      "size": ["atoms", "molecules"],
      "time": ["New Chemical Elements"],
      "teaches": ["chemical bonds","atomic structure","energy","covalent bonds","ionic bonds","periodic table", "hydrogen bonds", "electronegativity"],
      "is": ["video","Cassiopeia Project"],
      "discipline": ["Chemistry"],
      "username": "cassiopeiaproject",
      "rating": 4.86246395111,
      "description": "Find out more about Chemical Bonds!",
      "viewcount": 96761,
      "author": "cassiopeiaproject",
      "url": "https://www.youtube.com/watch?v=hEFeLYWTKX0",
      "title": "Chemical Bonds",
      "dislikes": 12,
      "bigthumb": "",
      "videoid": "hEFeLYWTKX0",
      "keywords": ["Chemistry", "chemical", "bond", "periodic", "table", "element", "atom", "molecule", "electron", "proton", "polar", "covalent", "orbital", "energy", "electronegat"],
      "length": 438,
      "likes": 337,
      "duration": "00:07:18",
      "thumb": "http://i.ytimg.com/vi/hEFeLYWTKX0/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["species"],
      "time": ["Modern Revolution"],
      "teaches": ["telescopes","Hubble Space Telescope","James Webb Space Telescope","light","infrared", "Giant Magellan Telescope (GMT)", "adaptive optics", "The Large Synoptic Survey Telescope (LSST)"],
      "is": ["video", "PBS Space Time"],
      "discipline": ["Physics","Cosmology"],
      "username": "PBS Space Time",
      "rating": 4.9619160964,
      "description": "Super telescopes are coming! Thanks to The Great Courses Plus for sponsoring this episode of Space Time. Try a 30 day trial of The Great Course Plus at http://ow.ly/Fxt1306GoOa NASA\u2019s Hubble Space Telescope is now 27 years old, but a new generation of telescopes are on their way. Find out about the James Webb Space Telescope, the Giant Magellan Telescope and the Large Synoptic Survey Telescope. \n\nYou can further support us on Patreon at https://www.patreon.com/pbsspacetime\nGet your own Space Time t\u00adshirt at http://bit.ly/1QlzoBi\nTweet at us! @pbsspacetime\nFacebook: facebook.com/pbsspacetime\nEmail us! pbsspacetime [at] gmail [dot] com\nComment on Reddit: http://www.reddit.com/r/pbsspacetime\n\nHelp translate our videos! https://www.youtube.com/timedtext_cs_panel?tab=2&c=UC7_gcs09iThXybpVgjHZ_7g\n\nThe telescopes of tomorrow will see in infrared and ultraviolet. They will peer through space and scan across time. They will allow us to find new supernovae, spot potentially hazardous asteroids, better understand dark energy and peer into the earliest moments of space time.  \n\nPrevious Episode\nThe Geometry of Causality\nhttps://www.youtube.com/watch?v=1YFrISfN7jo\n\nWritten by Alexandra Yep and Matt O\u2019Dowd\nHosted by Matt O\u2019Dowd\nProduced by Rusty Ward\nGraphics by Grayson Blackmon\nMade by Kornhaber Brown (www.kornhaberbrown.com)\n\nResources:\nThe James Webb Space Telescope https://jwst.nasa.gov\nThe Giant Magellan Telescope https://www.gmto.org/\nThe Large Synoptic Survey Telescope https://www.lsst.org\n\nComments Answered by Matt:\n\nLouis Anthes\nhttps://www.youtube.com/watch?v=1YFrISfN7jo&lc=z12pcp34szazy1qqz04cgvpg0sjnivjq0to0k\n\nQED\nhttps://www.youtube.com/watch?v=1YFrISfN7jo&lc=z131xd1xbrihsrdm3231i5fr0sz1yb2ff\n\n\nSpecial thanks to our Patreon Big Bang, Quasar and Hypernova Supporters: \n\nBig Bang\nHenry Van Styn\nDavid Nicklas\n\nQuasar\nJelle Slaets\nTambe Barsbay\nLuna IT Solutions\n\nHypernova\nCoolAsCats\nChuck Zegar\nCraig Peterson\nJordan Young\nRatfeast\nJohn Hofmann\n\nThanks to our Patreon Gamma Ray Burst Supporters: \nMichael Peanut-Karmi\nBernardo Higuera\nErik Stein\nDaniel Lyons\nAvan & Kyan Griggs\nJade Bilkey\nKevin Warne\nJJ Bagnell\nJ Rejc\nMichael Fischer\nDylan Merida\nAmy Jie\nAnthony Caridi\nAvi Goldfinger\nCorey Smeaton\nJohn Pettit\nShannan Catalano\nFlorian Stinglmayr\nYubo Du\nBenoit Pag\u00e9-Guitard\nRonny Polonia\nNathan Leniz\nJessica Fraley\nKirk Mathews\nLoro Lukic\nCarl P. Corliss\nBrandon labonte\nDavid Crane\nGreg Weiss\nEric Jackson",
      "viewcount": 261074,
      "author": "PBS Space Time",
      "url": "https://www.youtube.com/watch?v=CoQE5J346mU",
      "title": "Telescopes of Tomorrow | Space Time",
      "dislikes": 96,
      "bigthumb": "https://i.ytimg.com/vi/CoQE5J346mU/sddefault.jpg",
      "videoid": "CoQE5J346mU",
      "keywords": ["Space", "time", "space time", "pbs", "Physics", "astroPhysics", "Astronomy", "education", "science", "big bang", "comic microwave background", "radiation", "supernova", "telescopes", "telescope", "james webb telescope", "james webb", "giant magellan telescope", "lare synoptic survey telescope", "gmt", "lsst", "hubble", "hubble space telescope", "universe", "cosmos"],
      "length": 781,
      "likes": 9987,
      "duration": "00:13:01",
      "thumb": "http://i.ytimg.com/vi/CoQE5J346mU/default.jpg"
  }, {
      "dates": [],
      "tags": ["Edward Jenner"],
      "size": ["cells","organisms","species","biological community"],
      "time": [],
      "teaches": ["germ theory","vaccination","immune system","germs","disease"],
      "is": ["video","history"],
      "discipline": ["history","Biology","Molecular Biology"],
      "username": "NPR",
      "rating": 4.93043478261,
      "description": "For most of human history, we had a lot of bad ideas about how we were getting sick: angry gods, misaligned planets, stinky fumes. We also had plenty of bad ideas about how to prevent it, like bloodletting, large holes in the head and drinking arsenic.\n\nThings started changing only about 200 years ago. An English doctor named Edward Jenner decided to take a closer look at a promising folk remedy. (We'll leave the details for the video.) Eventually, he invented vaccination, our first safe and effective way to fight disease. About time!\n\nSo what did that do for us? Consider that in 1900, the average person lived only about 30 years. Today, most of us live to seventy. We were so successful in such a short time, the U.S. Surgeon General reportedly exclaimed in 1967 that we had closed the book on infectious disease.\n\nIf only! The history of humans and germs turns out to be way more complicated.\n\n\u2022 Visit http://npr.org/pandemic for more stories in this series\n\n------------------------------------------------------\n\nSubscribe to NPR on YouTube: https://www.youtube.com/npr\n\nFollow NPR elsewhere, too:\n\u2022 Twitter: https://twitter.com/npr\n\u2022 Facebook: https://www.facebook.com/NPR\n\u2022 Instagram: https://www.instagram.com/npr/\n\u2022 Tumblr: http://npr.tumblr.com/\n\u2022 Snapchat: https://www.snapchat.com/add/npr\n\nABOUT NPR\nNPR connects to audiences on the air, on demand, online, and in person. More than 26 million radio listeners tune in to NPR stations each week and more than 36 million unique visitors access NPR.org each month making NPR one of the most trusted sources of news and insights on life and the arts. NPR is also the leading publisher of podcasts, with 36 original shows and an average of 4 million listeners per week. NPR shares compelling stories, audio and photos with millions of social media users on Facebook, Twitter, Instagram, Pinterest, YouTube and Snapchat; NPR News and NPR One apps, online streaming, podcasts, iTunes radio and connected car dashboards help meet audiences where they are. NPR's live events bring to the stage two-way conversations between NPR hosts and the audience in collaboration with the public radio Member Station community. This robust access to public service journalism makes NPR an indispensable resource in the media landscape.",
      "viewcount": 23632,
      "author": "NPR",
      "url": "https://www.youtube.com/watch?v=xOFH57Do2EM",
      "title": "A Short History Of Humans And Germs: Humans Get A Clue | Goats & Soda | NPR",
      "dislikes": 4,
      "bigthumb": "https://i.ytimg.com/vi/xOFH57Do2EM/sddefault.jpg",
      "videoid": "xOFH57Do2EM",
      "keywords": ["npr", "pandemic", "epidemic", "germs", "history", "short history", "humans", "science", "history of science", "vaccination", "jenner", "ecohealth", "outbreak"],
      "length": 217,
      "likes": 226,
      "duration": "00:03:37",
      "thumb": "http://i.ytimg.com/vi/xOFH57Do2EM/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["cells","organisms","species","biological community"],
      "time": ["Agriculture"],
      "teaches": ["germ theory","immune system","germs","disease"],
      "is": ["video","history"],
      "discipline": ["history","Biology","Molecular Biology"],
      "username": "NPR",
      "rating": 4.94920634921,
      "description": "Humans get along pretty well with most microbes. Which is lucky, because there are a lot more of them in the world than there are of us. We couldn\u2019t even live without many of them. But a few hundred have evolved, and are still evolving, to exploit our bodies in ways that can make us really sick. These are the microbes we call germs. Think  plague, HIV, SARS, Ebola, Zika, measles.\n\nThis is a series is about where germs come from.  In this first of three episodes, we see what our early encounters with germs may have been like, and how germs initially got an upper hand.\n\n-----------------\n\nSubscribe to NPR on YouTube: https://www.youtube.com/npr\n\nFollow NPR elsewhere, too:\n\u2022 Twitter: https://twitter.com/npr\n\u2022 Facebook: https://www.facebook.com/NPR\n\u2022 Instagram: https://www.instagram.com/npr/\n\u2022 Tumblr: http://npr.tumblr.com/\n\u2022 Snapchat: https://www.snapchat.com/add/npr\n\nABOUT NPR\nNPR connects to audiences on the air, on demand, online, and in person. More than 26 million radio listeners tune in to NPR stations each week and more than 36 million unique visitors access NPR.org each month making NPR one of the most trusted sources of news and insights on life and the arts. NPR is also the leading publisher of podcasts, with 36 original shows and an average of 4 million listeners per week. NPR shares compelling stories, audio and photos with millions of social media users on Facebook, Twitter, Instagram, Pinterest, YouTube and Snapchat; NPR News and NPR One apps, online streaming, podcasts, iTunes radio and connected car dashboards help meet audiences where they are. NPR's live events bring to the stage two-way conversations between NPR hosts and the audience in collaboration with the public radio Member Station community. This robust access to public service journalism makes NPR an indispensable resource in the media landscape.",
      "viewcount": 46376,
      "author": "NPR",
      "url": "https://www.youtube.com/watch?v=Utcn6LGYHSI",
      "title": "A Short History Of Humans And Germs: Early Encounters | Goats & Soda | NPR",
      "dislikes": 4,
      "bigthumb": "https://i.ytimg.com/vi/Utcn6LGYHSI/sddefault.jpg",
      "videoid": "Utcn6LGYHSI",
      "keywords": ["npr", "science", "goatsandsoda", "microbes", "germs", "epidemic", "history", "outbreak", "contagion", "pandemic"],
      "length": 161,
      "likes": 311,
      "duration": "00:02:41",
      "thumb": "http://i.ytimg.com/vi/Utcn6LGYHSI/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["cells","organisms","species","biological community"],
      "time": ["Agriculture"],
      "teaches": ["germ theory","germs","disease"],
      "is": ["video","history"],
      "discipline": ["history","Biology","Molecular Biology"],
      "username": "NPR",
      "rating": 5.0,
      "description": "Ten thousand years ago, at the dawn of the agricultural revolution, many of our deadly human diseases didn't exist. What changed?\n\nFor the first time in history, humans were living in close contact with domesticated animals - milking them, taking care of them, living with them and eating them. All that touching and sharing gave animal germs plenty of chances to get inside of us.\n\nTake measles. Researchers think that up until about 5,000 years ago, it didn\u2019t exist. But its older cousin Rinderpest, a cattle disease, did. Now that humans were spending so much quality time with cows, little Rinderpest germs started jumping over into us. And a few of them had a lucky mutation that allowed Rinderpest to evolve from a cattle disease into measles, a deadly human virus.\n\nBut our ancestors had no idea what the problem was - or how to fix it. See how humans finally get a clue, in  Episode 3, coming Feb. 16.\n\nWatch Episode 1: A Short History of Humans and Germs: Early Encounters https://www.youtube.com/watch?v=Utcn6LGYHSI\nAnd see what new viruses are emerging in your backyard: http://n.pr/2lr8mRf\n\n\n------------------------------------------------------\n\nSubscribe to NPR on YouTube: https://www.youtube.com/npr\n\nFollow NPR elsewhere, too:\n\u2022 Twitter: https://twitter.com/npr\n\u2022 Facebook: https://www.facebook.com/NPR\n\u2022 Instagram: https://www.instagram.com/npr/\n\u2022 Tumblr: http://npr.tumblr.com/\n\u2022 Snapchat: https://www.snapchat.com/add/npr\n\nABOUT NPR\nNPR connects to audiences on the air, on demand, online, and in person. More than 26 million radio listeners tune in to NPR stations each week and more than 36 million unique visitors access NPR.org each month making NPR one of the most trusted sources of news and insights on life and the arts. NPR is also the leading publisher of podcasts, with 36 original shows and an average of 4 million listeners per week. NPR shares compelling stories, audio and photos with millions of social media users on Facebook, Twitter, Instagram, Pinterest, YouTube and Snapchat; NPR News and NPR One apps, online streaming, podcasts, iTunes radio and connected car dashboards help meet audiences where they are. NPR's live events bring to the stage two-way conversations between NPR hosts and the audience in collaboration with the public radio Member Station community. This robust access to public service journalism makes NPR an indispensable resource in the media landscape.",
      "viewcount": 50210,
      "author": "NPR",
      "url": "https://www.youtube.com/watch?v=9bsqLmwAq-w",
      "title": "A Short History Of Humans And Germs: The Golden Age Of Germs | Goats & Soda | NPR",
      "dislikes": 0,
      "bigthumb": "https://i.ytimg.com/vi/9bsqLmwAq-w/sddefault.jpg",
      "videoid": "9bsqLmwAq-w",
      "keywords": ["npr", "germs", "contagion", "disease", "history", "virus", "pandemic", "superspreader", "viruses", "a short history", "golden age", "age of discovery", "measles"],
      "length": 176,
      "likes": 293,
      "duration": "00:02:56",
      "thumb": "http://i.ytimg.com/vi/9bsqLmwAq-w/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ['fundamental particles and forces'],
      "time": ['big bang'],
      "teaches": ["wave-particle duality","uncertainty principal","wave function"],
      "is": ["video","simulation"],
      "discipline": ['quantum mechancis','Physics'],
      "username": "udiprod",
      "rating": 4.93954168698,
      "description": "This video visually demonstrates some basic quantum Physics concepts using the simple case of a free particle. \n\nAll the simulations here are based on real equations and laws. See more information here: http://www.zutopedia.com/quantum_Physics.html\n\nThe Mathematics involved was taken from this excellent book:\nhttps://www.amazon.com/exec/obidos/ASIN/0387989293/visualquantummec",
      "viewcount": 138877,
      "author": "udiprod",
      "url": "https://www.youtube.com/watch?v=p7bzE1E5PMY",
      "title": "Visualization of Quantum Physics (Quantum Mechanics)",
      "dislikes": 62,
      "bigthumb": "https://i.ytimg.com/vi/p7bzE1E5PMY/sddefault.jpg",
      "videoid": "p7bzE1E5PMY",
      "keywords": ["quantum Physics", "animation", "quantum mechanics", "Physics", "popular science"],
      "length": 874,
      "likes": 4040,
      "duration": "00:14:34",
      "thumb": "http://i.ytimg.com/vi/p7bzE1E5PMY/default.jpg"
  }, {
      "dates": [],
      "tags": ["Charles Babbage","Difference Engine","Analytical Engine"],
      "size": ["organisms","species"],
      "time": ["Modern Revolution"],
      "teaches": ["computing"],
      "is": ["video","history"],
      "discipline": ["computer science"],
      "username": "CrashCourse",
      "rating": 4.94163892627,
      "description": "Hello, world! Welcome to Crash Course Computer Science! So today, we\u2019re going to take a look at computing\u2019s origins, because even though our digital computers are relatively new, the need for computation is not. Since the start of civilization itself, humans have had an increasing need for special devices to help manage laborious tasks, and as the scale of society continued to grow, these computational devices began to play a crucial role in amplifying our mental abilities. From the abacus and astrolabe to the difference engine and tabulating machine, we\u2019ve come a long way to satisfying this increasing need, and in the process completely transformed commerce, government, and daily life. \n\nProduced in collaboration with PBS Digital Studios: http://youtube.com/pbsdigitalstudios\n\nWant to know more about Carrie Anne?\nhttps://about.me/carrieannephilbin\n\nWant more Crash Course in person? We'll be at NerdCon: Nerdfighteria in Boston on February 25th and 26th! For more information, go to http://www.nerdconnerdfighteria.com/\n\nThe Latest from PBS Digital Studios: https://www.youtube.com/playlist?list...\n\nWant to find Crash Course elsewhere on the internet?\nFacebook - http://www.facebook.com/YouTubeCrashC...\nTwitter - http://www.twitter.com/TheCrashCourse\nTumblr - http://thecrashcourse.tumblr.com \nSupport Crash Course on Patreon: http://patreon.com/crashcourse\n\nCC Kids: http://www.youtube.com/crashcoursekids",
      "viewcount": 286061,
      "author": "CrashCourse",
      "url": "https://www.youtube.com/watch?v=O5nskjZ_GoI",
      "title": "Early Computing: Crash Course Computer Science #1",
      "dislikes": 206,
      "bigthumb": "https://i.ytimg.com/vi/O5nskjZ_GoI/sddefault.jpg",
      "videoid": "O5nskjZ_GoI",
      "keywords": ["John Green", "Hank Green", "vlogbrothers", "Crash Course", "crashcourse", "education", "computers", "computation", "computer science", "electronic age", "history", "Mesopotamia", "Astrolabe", "abacus", "Hollerith machine", "step reckoner", "tabulating machine", "Charles Babbage", "ada Lovelace", "Katherine Johnson", "international business machines", "ibm", "range tables", "difference engine", "analytical engine", "census", "Herman Hollerith", "punch cards"],
      "length": 713,
      "likes": 13913,
      "duration": "00:11:53",
      "thumb": "http://i.ytimg.com/vi/O5nskjZ_GoI/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["planetary bodies","solar systems"],
      "time": ["Earth and the Solar System"],
      "teaches": ['fomelhaut',"protoplanetary disc","protostar","core accretion","Nice Model","planet formation","solar sytem formation"],
      "is": ["video","beginning","PBS Space Time"],
      "discipline": ["Astronomy"],
      "username": "PBS Space Time",
      "rating": 4.92965587045,
      "description": "Fomalhaut is a massive young star surrounded by a ring of dust debris that can tell us a great deal about the formation of our own solar system. Get your first two months of Curiosity Stream free by going to http://curiositystream.com/spacetime and using the promo code \u201cspacetime\u201d.\n\nYou can further support us on Patreon at https://www.patreon.com/pbsspacetime\nGet your own Space Time t\u00adshirt at http://bit.ly/1QlzoBi\nTweet at us! @pbsspacetime\nFacebook: facebook.com/pbsspacetime\nEmail us! pbsspacetime [at] gmail [dot] com\nComment on Reddit: http://www.reddit.com/r/pbsspacetime\n\nHelp translate our videos! https://www.youtube.com/timedtext_cs_panel?tab=2&c=UC7_gcs09iThXybpVgjHZ_7g\n\nFomalhaut is an awe-inspiring star that could unlock many mysteries concerning how our own solar system formed.\n\nPrevious Episode\nTelescopes of Tomorrow\nhttps://www.youtube.com/watch?v=CoQE5J346mU\n\nWritten by Alexandra Yep and Matt O\u2019Dowd\nHosted by Matt O\u2019Dowd\nProduced by Rusty Ward\nGraphics by Grayson Blackmon\nMade by Kornhaber Brown (www.kornhaberbrown.com)\n\nSources:\nA Planetary System as the Origin of Structure in Fomalhaut\u2019s Dust Belt\nKalas, Graham & Clampin (2005)\nhttps://arxiv.org/abs/astro-ph/0506574\n\nSTIS Coronographic Imaging OF Fomalhaut: Main Belt Structure and teh Orbit of Fomalhaut b\nKalas, Graham ,Fitzgerald & Clampin (2013)\nhttp://iopscience.iop.org/article/10.1088/0004-637X/775/1/56\n\nInfrared Non-detection of Fomalhaut b -- Implications for the Planet Interpretation\nJanson, Carson, Lafreniere, Spiegel, Bent & Wong (2012)\nhttps://arxiv.org/abs/1201.4388\n\nSpecial thanks to our Patreon Big Bang, Quasar and Hypernova Supporters: \n\nBig Bang\nHenry Van Styn\nDavid Nicklas\n\nQuasar\nTambe Barsbay\nLuna IT Solutions\n\nHypernova\nCoolAsCats (The Patron formerly known as Joe)\nChuck Zegar\nCraig Peterson\nJordan Young\nRatfeast\nJohn Hofmann\n\nThanks to our Patreon Gamma Ray Burst Supporters: \nMichal-Peanut Karmi\nBernardo Higuera\nErik Stein\nDaniel Lyons\nAvan & Kyan Griggs\nJade Bilkey\nKevin Warne\nJJ Bagnell\nJ Rejc\nMichael Fischer\nDylan Merida\nAmy Jie\nAnthony Caridi\nAvi Goldfinger\nCorey Smeaton\nJohn Pettit\nShannan Catalano\nFlorian Stinglmayr\nYubo Du\nBenoit Pag\u00e9-Guitard\nRonny Polonia\nNathan Leniz\nJessica Fraley\nKirk Mathews\nLoro Lukic\nCarl P. Corliss\nBrandon labonte\nDavid Crane\nGreg Weiss\nEric Jackson",
      "viewcount": 256013,
      "author": "PBS Space Time",
      "url": "https://www.youtube.com/watch?v=TQZyaMRp7_0",
      "title": "The Eye of Sauron Reveals a Forming Solar System! | Space Time",
      "dislikes": 139,
      "bigthumb": "https://i.ytimg.com/vi/TQZyaMRp7_0/sddefault.jpg",
      "videoid": "TQZyaMRp7_0",
      "keywords": ["stars", "star", "astroPhysics", "Physics", "Astronomy", "space", "time", "space time", "education", "science", "planettessimal", "planet", "sun", "solar system", "jupiter", "hot jupiter", "star formation", "fomelhaut", "fomelhaut b", "dagon", "coronagraph", "alma", "discovery", "earth-like planets", "nasa"],
      "length": 647,
      "likes": 7765,
      "duration": "00:10:47",
      "thumb": "http://i.ytimg.com/vi/TQZyaMRp7_0/default.jpg"
  }, {
      "dates": [],
      "tags": ["Artifical intelligence","robots"],
      "size": ["species","organisms"],
      "time": ["Modern Revolution"],
      "teaches": ["rights","morality"],
      "is": ["video"],
      "discipline": ["Philosophy","Ethics"],
      "username": "Kurzgesagt \u2013 In a Nutshell",
      "rating": 4.89524416773,
      "description": "What shall we do once machines become conscious? Do we need to grant them rights?\n\nCheck out Wisecrack and their video:  https://goo.gl/oaUbAF\n\n'The Philosophy of Westworld': https://goo.gl/8Tn2m5\n\nSupport us on Patreon so we can make more videos (and get cool stuff in return): https://www.patreon.com/Kurzgesagt?ty=h\n\nKurzgesagt merch here:  http://bit.ly/1P1hQIH\n\nGet the music of the video here: \n\nSoundcloud: http://bit.ly/2loQhFv\nBandcamp: http://bit.ly/2mlxs3q\nFacebook: https://www.facebook.com/epic-mountain-music\n\n\nTHANKS A LOT TO OUR LOVELY PATRONS FOR SUPPORTING US:\n\nMarius Guran, BrightKnight, Torbj\u00f8rn Lundstr\u00f8m, Cameron Lilley, Dennis J Trammell, Valentino Gantz, Jonas Hejde, Oliver Emberton, Zsolt Kocsi, \u201a@B_Strohmayer, Sumesh Thakur, Josh Webb, Arron Creswell, Sultan Alkhulaifi, Carminatti, Everett Greenwood, Ahmed Abduljabar, Mel Osborne, Alex Rozumiy, Isabel Garcia, Darnell holder, Emma, Jorge Emilio Santaella Glez, Jan Jacobsen, Sven Kr\u00e4mer, Philipp Gagel, Kyle Myers, Phillip Blackwell, Matthias Opsomer, Eduardo Santos, Vasilios Bikoulis, punch, James Hornby, Briana Hunt, Moch Faisal Rasid, Alexandru Bitca, Ben Thayer, Adam Spangler, Franz Palomares, Thomas van Gulick, Ryan Nightingale, Kedar Deshpande, Joseph Markham, Pascal Schmidt, Devashish Shanker, Aschwin Berkhout, Aaron Taylor, Gon\u00e7alo Marques, Ronald Susanto, Joseph stachow, David Darking, Alexander Jo, Niels lagcher, jackattack22, Luke Simmons, Hunter Gatewood, Mary Duhig, Johann Pardanaud, Martin Machava, Henkou, Ben Thompson, Danny Shaw, JI DE YI, James Turner,Jodi Doherty, Simon Pyne, Kim Home, elliot ward, G, Daniel Moul, Alan Huang, Jonathan Ling\n\nHelp us caption & translate this video!\n\nhttp://www.youtube.com/timedtext_cs_panel?c=UCsXVk37bltHxD1rDPwtNM8Q&tab=2\n\nDo Robots Deserve Rights? What if machines become conscious?",
      "viewcount": 2202564,
      "author": "Kurzgesagt \u2013 In a Nutshell",
      "url": "https://www.youtube.com/watch?v=DHyUYg8X31c",
      "title": "Do Robots Deserve Rights? What if Machines Become Conscious?",
      "dislikes": 2793,
      "bigthumb": "https://i.ytimg.com/vi/DHyUYg8X31c/sddefault.jpg",
      "videoid": "DHyUYg8X31c",
      "keywords": ["robots", "ai", "singularity", "artificial intelligence", "morals", "laws", "westworld"],
      "length": 395,
      "likes": 103855,
      "duration": "00:06:35",
      "thumb": "http://i.ytimg.com/vi/DHyUYg8X31c/default.jpg"
  }, {
      "dates": [],
      "tags": ["kamal","stick chart","compass","ocean","astrolabe","lodestone","calcite"],
      "size": ["organims","species"],
      "time": ["Collective Learning"],
      "teaches": ["navigation","human migration","tools"],
      "is": ["video","history"],
      "discipline": ["Sociology","Anthropology"],
      "username": "SciShow",
      "rating": 4.96432062561,
      "description": "People have been exploring the oceans since prehistoric times, way before they had GPS to help them figure out where they were. Here are 6 ingenious ways our ancestors navigated the oceans.\n\nHosted by: Hank Green\n----------\nSupport SciShow by becoming a patron on Patreon: https://www.patreon.com/scishow\n----------\nDooblydoo thanks go to the following Patreon supporters\u2014we couldn't make SciShow without them! Shout out to Kevin Bealer, Mark Terrio-Cameron, KatieMarie Magnone, Patrick Merrithew, Charles Southerland, Fatima Iqbal, Benny, Kyle Anderson, Tim Curwick, Scott Satovsky Jr, Will and Sonja Marple, Philippe von Bergen, Bella Nash, Bryce Daifuku, Chris Peters, Patrick D. Ashmore, Charles George, Bader AlGhamdi\n----------\nLooking for SciShow elsewhere on the internet?\nFacebook: http://www.facebook.com/scishow\nTwitter: http://www.twitter.com/scishow\nTumblr: http://scishow.tumblr.com\nInstagram: http://instagram.com/thescishow\n----------\nSources:\nhttp://ageofex.marinersmuseum.org/index.php?type=navigationtool&id=14\nhttp://www.surveyhistory.org/jacob's_staff1.htm\nhttp://www.vos.noaa.gov/MWL/aug_08/navigation_tools.shtml\nhttp://www.Math.nus.edu.sg/aslaksen/gem-projects/hm/0203-1-10-instruments/cross_staff.htm\nhttp://www.smithsonianmag.com/smithsonian-institution/how-sticks-and-shell-charts-became-sophisticated-system-navigation-180954018/\nhttp://www.metmuseum.org/toah/works-of-art/1978.412.826/\nhttp://ageofex.marinersmuseum.org/index.php?type=navigationtool&id=10\nhttp://www.independent.co.uk/news/science/archaeology/not-just-the-stuff-of-legend-famed-viking-sunstone-did-exist-believe-scientists-8521522.html\nhttp://www.sciencemag.org/news/2011/11/viking-sunstone-revealed\nhttp://www.livescience.com/27696-viking-sunstone-shipwreck.html\nhttp://www.visiteskifjordur.is/icelandic-spar/iceland-spar-vikings-use-navigation/\nhttp://www.oceannavigator.com/January-February-2003/Arab-navigators-used-a-Kamal-to-find-latitude/\nhttp://exploration.marinersmuseum.org/object/kamal/\nhttp://www.nature.com/nature/journal/v459/n7248/full/459778a.html\nhttp://www.cultural-china.com/chinaWH/html/en/History206bye774.html\nhttp://afe.easia.columbia.edu/special/china_1000ce_mingvoyages.htm\nhttp://nationalgeographic.org/encyclopedia/compass/\nhttp://hyperPhysics.phy-astr.gsu.edu/hbase/phyopt/biref.html\nhttps://www.astrolabes.org/pages/mariner.htm\nhttp://exploration.marinersmuseum.org/object/astrolabe/\nhttp://ageofex.marinersmuseum.org/index.php?type=navigationtool&id=12\nhttp://www.sciencemag.org/news/2014/10/epic-pre-columbian-voyage-suggested-genes\nhttp://www.newworldencyclopedia.org/entry/Compass\nhttp://www.livescience.com/32732-how-does-a-compass-work.html\nhttp://galileo.rice.edu/sci/observations/longitude.html\nhttp://www.pbs.org/weta/roughscience/series1/challenges/latlong/page4.html\nhttps://www.timeanddate.com/Astronomy/tell-time-by-stars.html\nhttp://www.pbs.org/wayfinders/polynesian6.html\nhttps://www.quora.com/Why-is-the-light-coming-from-the-sun-semi-polarized-Is-it-because-of-the-Faraday-rotation\nhttp://www.olympusmicro.com/primer/lightandcolor/birefringence.html\nhttps://books.google.com/books?id=5VAVDAAAQBAJ&pg=PA288&\nhttp://www.sciencedirect.com/science/article/pii/S0315086085710300\nhttp://www.tandfonline.com/doi/abs/10.1080/03085696008592173?journalCode=rimu20\nhttps://www.britannica.com/place/Marshall-Islands",
      "viewcount": 216025,
      "author": "SciShow",
      "url": "https://www.youtube.com/watch?v=2Bv8dc19HQ0",
      "title": "6 Creative Ways People Used to Navigate the Oceans",
      "dislikes": 73,
      "bigthumb": "https://i.ytimg.com/vi/2Bv8dc19HQ0/sddefault.jpg",
      "videoid": "2Bv8dc19HQ0",
      "keywords": ["SciShow", "science", "Hank", "Green", "education", "learn", "navigation", "ocean", "sunstone", "viking", "compass", "lodestone", "stick chart", "sailing", "sailor", "mariner", "boat", "ship", "pacific", "micronesia", "marshall islands", "kamal", "north star", "polaris", "direction", "magnet", "latitude", "astrolabe", "china", "navy", "ming dynasty", "history", "calcite", "light", "refraction", "explore", "iceland"],
      "length": 628,
      "likes": 8111,
      "duration": "00:10:28",
      "thumb": "http://i.ytimg.com/vi/2Bv8dc19HQ0/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["species"],
      "time": ["Modern Revolution"],
      "teaches": ["The Internet","arpanet","Domain Name System (DNS)","Packet Switching"],
      "is": ["video","history","beginning"],
      "discipline": ["Computer Science"],
      "username": "SciShow",
      "rating": 4.69104245388,
      "description": "The Internet is older than you might think!\n\nHosted by: Olivia Gordon\n----------\nSupport SciShow by becoming a patron on Patreon: https://www.patreon.com/scishow\n----------\nDooblydoo thanks go to the following Patreon supporters\u2014we couldn't make SciShow without them! Shout out to Kevin Bealer, Mark Terrio-Cameron, KatieMarie Magnone, Patrick Merrithew, Charles Southerland, Fatima Iqbal, Benny, Kyle Anderson, Tim Curwick, Scott Satovsky Jr, Will and Sonja Marple, Philippe von Bergen, Bella Nash, Bryce Daifuku, Chris Peters, Patrick D. Ashmore, Charles George, Bader AlGhamdi\n----------\nLooking for SciShow elsewhere on the internet?\nFacebook: http://www.facebook.com/scishow\nTwitter: http://www.twitter.com/scishow\nTumblr: http://scishow.tumblr.com\nInstagram: http://instagram.com/thescishow\n----------\nSources:\nhttp://royal.pingdom.com/2008/04/11/map-of-all-google-data-center-locations/\nhttps://web.archive.org/web/20120129120350/http://www.tildefrugal.net/tech/arp.php \nhttp://www.gartner.com/newsroom/id/3165317 \nhttp://www.atomicheritage.org/history/computing-and-manhattan-project \nhttps://amazon.com/Pleasure-Finding-Things-Out-Richard/dp/0465023959/ \nhttps://www.dlsweb.rmit.edu.au/set/Courses/Content/CSIT/oua/cpt160/2014sp4/chapter/10/ErrorCorrectionRedundancy.html \nhttps://books.google.com/books?id=5Jaa1BVverIC&pg=PA700\nhttp://www.pcmag.com/article2/0,2817,2372163,00.asp \nhttp://www.livinginternet.com/i/ii_darpa.htm \nhttps://www.zakon.org/robert/internet/timeline/ \nhttp://www.packet.cc/files/toward-coop-net.html \nhttp://www.unr.edu/cse/prospective-students/what-is-networking\nhttp://firstmonday.org/ojs/index.php/fm/article/view/612/533 \nhttp://www.historyofcomputercommunications.info/Book/2/2.8-The%20RFQ%20and%20Bidding68.html \nhttps://www.sri.com/work/timeline-innovation/timeline.php?timeline=computing-digital#!&innovation=arpanet \nhttp://www.livinginternet.com/i/ii_arpanet.htm\nhttp://www.packet.cc/files/ev-packet-sw.html\nhttp://searchnetworking.techtarget.com/definition/routing-table\nhttps://www.computer.org/csdl/proceedings/afips/1972/5079/00/50790243.pdf\nhttp://www.cs.ucsb.edu/~almeroth/classes/F04.176A/homework1_good_papers/jay-akkad.html\nhttps://www.cs.rutgers.edu/~pxk/352/exam/study-guide-final.html\nhttps://www.computer.org/csdl/mags/it/2014/03/mit2014030066-abs.html\nhttps://books.google.com/books?id=6KPMBQAAQBAJ&pg=PA18\nhttp://www.historyofcomputercommunications.info/Book/2/2.3-Circuit%20Switching.html \nhttp://privateline.com/?page_id=303 \nhttp://mason.gmu.edu/~afinn/html/tele/tech%20chapters/T12.htm \nhttp://ethw.org/Electromechanical_Telephone-Switching\nhttps://www.nytimes.com/2016/02/18/technology/personaltech/free-tools-to-keep-those-creepy-online-ads-from-watching-you.html\nhttp://www.science.smith.edu/~jcardell/Courses/EGR328/Readings/KuroseRoss%20Ch1.pdf \nhttp://www.rand.org/content/dam/rand/pubs/research_memoranda/2006/RM3420.pdf \nhttp://www.rand.org/pubs/research_memoranda/RM3420.html \nhttp://www.historyofcomputercommunications.info/Book/2/2.2-TheSeminalExperiment-65.html\nhttp://www.livinginternet.com/i/iw_packet_inv.htm\nhttp://www.historyofcomputercommunications.info/Book/2/2.7-PlanningARPANET67-68.html \nhttp://www.livinginternet.com/i/ii_imp.htm\nhttp://www.livinginternet.com/i/ii_imp_walden.htm\nhttp://www.livinginternet.com/i/iw_dns_history.htm \nhttp://www.computerhistory.org/internethistory/1970s/\nhttp://nrg.cs.ucl.ac.uk/internet-history.html \nhttp://www.livinginternet.com/i/ii_arpanet_gateways.htm\nhttp://www.nethistory.info/History%20of%20the%20Internet/beginnings.html \nhttp://www.hostingadvice.com/blog/tcpip-make-internet-work/\nhttp://searchnetworking.techtarget.com/definition/TCP-IP \nhttp://www.ifa.hawaii.edu/users/gmm/intro_ip/sec1.html \nhttp://www.computerhistory.org/internethistory/1980s/\nhttp://www.columbia.edu/~hauben/CS/arpanet-encyc.txt \nhttp://www.livinginternet.com/i/ii_tcpip.htm \nhttps://www.cs.umd.edu/class/spring2002/cmsc434-0101/MUIseum/applications/firstemail.html\nhttp://www.tldp.org/LDP/nag/node189.html \nhttp://www.livinginternet.com/References/Ian%20Hardy%20Email%20Thesis.txt\nhttp://www.livinginternet.com/e/ew_addr.htm \nhttps://technet.microsoft.com/en-us/library/2005.01.howitworksdns.aspx \nhttp://www.internetsociety.org/internet/what-internet/history-internet/brief-history-internet\nhttp://www.webhostingsearch.com/articles/history-of-domains-names.php \nhttp://www-Math.mit.edu/~steng/18.996/lecture2_mit.pdf\nhttp://www.academia.edu/1416892/Getting_Started_Computing_at_the_AI_Lab \nhttps://books.google.com/books?id=cla-CgAAQBAJ&pg=PA28\nImages:\nhttps://commons.wikimedia.org/w/index.php?title=File:ARPANET_Info_Brochure.pdf&page=21#filelinks\nhttps://commons.wikimedia.org/wiki/File:J._C._R._Licklider.jpg\nhttps://upload.wikimedia.org/wikipedia/commons/5/50/Telephone_operators%2C_1952.jpg",
      "viewcount": 188383,
      "author": "SciShow",
      "url": "https://www.youtube.com/watch?v=1UStbvRnwmQ",
      "title": "How the Internet Was Invented | The History of the Internet, Part 1",
      "dislikes": 695,
      "bigthumb": "https://i.ytimg.com/vi/1UStbvRnwmQ/sddefault.jpg",
      "videoid": "1UStbvRnwmQ",
      "keywords": ["SciShow", "science", "Hank", "Green", "education", "learn", "history", "internet", "part", "one", "computer", "network", "darpa", "arpa", "arpanet", "olivia", "gordon"],
      "length": 697,
      "likes": 8303,
      "duration": "00:11:37",
      "thumb": "http://i.ytimg.com/vi/1UStbvRnwmQ/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["The Universe","Observable Universe"],
      "time": ["Big Bang"],
      "teaches": ["Horizon Problem","Space","Cosmic Inflation","Speed of Light"],
      "is": ["video"],
      "discipline": ["Cosmology","Physics"],
      "username": "New Scientist",
      "rating": 4.87368421053,
      "description": "In an expanding universe, bits of the far-flung cosmos could never have been in contact with each other. So why do they all look the same?\n\nRead the whole story at https://www.newscientist.com/round-up/cosmic-uncertainty/",
      "viewcount": 8598,
      "author": "New Scientist",
      "url": "https://www.youtube.com/watch?v=axrbSOFIdnk",
      "title": "The horizon problem - why does the universe look the same in all directions?",
      "dislikes": 6,
      "bigthumb": "https://i.ytimg.com/vi/axrbSOFIdnk/sddefault.jpg",
      "videoid": "axrbSOFIdnk",
      "keywords": ["science", "Physics", "space", "Cosmology", "horizon problem", "new scientist", "animation"],
      "length": 151,
      "likes": 184,
      "duration": "00:02:31",
      "thumb": "http://i.ytimg.com/vi/axrbSOFIdnk/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["species"],
      "time": ["Modern Revolution"],
      "teaches": ["Legal System","Jury","Law"],
      "is": ["video"],
      "discipline": ["Sociology","Government"],
      "username": "TED-Ed",
      "rating": 4.87229660144,
      "description": "View full lesson: http://ed.ted.com/lessons/what-happened-to-trial-by-jury-suja-a-thomas\n\nIn the United States today, juries decide less than 4% of criminal cases and less than 1% of civil cases filed in court. At the same time, jury systems in other countries are growing. So what happened in the US? And could the disappearance of juries be a good thing? Suja A. Thomas explores both sides of this dilemma. \n\nLesson by Suja A. Thomas, animation by Globizco.",
      "viewcount": 226483,
      "author": "TED-Ed",
      "url": "https://www.youtube.com/watch?v=qVoYFYxGJPg",
      "title": "What happened to trial by jury? - Suja A. Thomas",
      "dislikes": 186,
      "bigthumb": "https://i.ytimg.com/vi/qVoYFYxGJPg/sddefault.jpg",
      "videoid": "qVoYFYxGJPg",
      "keywords": ["TED", "TED-Ed", "TED Ed", "TED Education", "Suja A. Thomas", "Globizco", "jury", "trial", "trial by jury", "legal system", "judge", "legislative branch", "constitution", "plea bargain", "Supreme Court", "summary judgment", "civil case", "criminal case", "arbitration", "bias"],
      "length": 252,
      "likes": 5640,
      "duration": "00:04:12",
      "thumb": "http://i.ytimg.com/vi/qVoYFYxGJPg/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Symbols"],
      "time": [],
      "teaches": ["Infinity","ordinals","cardinals","aleph","numbers","Set Theory"],
      "is": ["video"],
      "discipline": ["Math"],
      "username": "Vsauce",
      "rating": 4.8933938139,
      "description": "my twitter: @tweetsauce\nmy instagram: electricpants\n\nSources and links to learn more below!\n\nI\u2019m very grateful to Mathematician Hugh Woodin, Professor of Philosophy and Mathematics at Harvard, for taking the time on multiple occasions to discuss this topic with me and help me wrap my (finite) head around it.\n\nI\u2019m also grateful to David Eisenbud, the Director of the Mathematical Sciences Research Institute (MSRI) and professor of Mathematics at the University of California, Berkeley, for his help and for connecting me with Hugh Woodin.\n\nAnd of course, big thanks to Brady Haran who created the \u201cmile of pi\u201d seen in this video and connected me with all these Mathematicians in the first place. His channel, Numberphile, is superb: https://www.youtube.com/user/numberphile\n\nBOOKS related to these topics that I used:\n\n\u201cThe Outer Limits of Reason\u201d by Noson S. Yanofsky: http://amzn.com/0262019353\n\u201cInfinity and The Mind\u201d by Rudy Rucker: http://amzn.com/0691121273\n\u201cRoads to Infinity\u201d by John C. Stilwell: http://amzn.com/1568814666\n\u201cMore Precisely: The Math You Need to Do Philosophy\u201d by Eric Steinhart: http://amzn.com/1551119099\n\u201cSatan, Cantor and Infinity: Mind-Boggling Puzzles\u201d by Raymond M. Smullyan: http://amzn.com/0486470369\n\nclassic book that helps introduce concept of axioms: \u201cIntroduction to the Foundations of Mathematics\u201d by Raymond L. Wilder: http://amzn.com/0486488209\n\nHugh Woodin speaking about infinity at the World Science Festival: https://youtu.be/KDCJZ81PwVM?t=29m45s\n\nNames of large (finite) numbers: https://en.wikipedia.org/wiki/Names_of_large_numbers\n\nGeoglyphs:\n\nThe biggest number: https://goo.gl/maps/7GWcpnzo7iG2\n\nFovant badges: https://en.wikipedia.org/wiki/Fovant_Badges\n\nBattalion Park: https://en.wikipedia.org/wiki/Battalion_Park\n\nA mile of pi [VIDEO]: https://www.youtube.com/watch?v=0r3cEKZiLmg\n\nWikipedia\u2019s great visualization of ordinals out to omega^omega: https://en.wikipedia.org/wiki/File:Omega-exp-omega-labeled.svg\n\nas seen on: https://en.wikipedia.org/wiki/Ordinal_number\n\nthis is also a good page about ordinals: http://Math.wikia.com/wiki/Ordinal_Number\n\nalso: http://www.cut-the-knot.org/WhatIs/Infinity/Ordinals.shtml\n\nand: https://en.wikipedia.org/wiki/Order_type and https://en.wikipedia.org/wiki/Well-order\n\nAxioms: \nhttps://en.wikipedia.org/wiki/Axiom\nhttps://www.reddit.com/r/askscience/comments/30xokb/have_there_been_axioms_that_later_have_been/\nhttp://philosophy.stackexchange.com/questions/5922/what-is-the-difference-between-dogma-and-an-axiom\nhttp://www.cs.umd.edu/~gasarch/BLOGPAPERS/belaxioms1.pdf\nhttp://www.cs.umd.edu/~gasarch/BLOGPAPERS/belaxioms2.pdf\n\nTHE UNREASONABLE EFFECTIVENSS OF MathEMATICS IN THE NATURAL SCIENCES\n[PDF]: http://www.Maths.ed.ac.uk/~aar/papers/wigner.pdf\nhttps://en.wikipedia.org/wiki/The_Unreasonable_Effectiveness_of_Mathematics_in_the_Natural_Sciences\n\nLarge Cardinal game based on 2048: http://cantorontheshore.blogspot.it/2014/10/one-reinhardt-and-counting.html\n\nOther good resources:\n\nhttp://quibb.blogspot.com/2012/01/infinity-first-transfinite-cardinal.html\nhttp://plato.stanford.edu/entries/set-theory/\nhttp://cantorsattic.info/Cantor%27s_Attic\nhttp://cantorontheshore.blogspot.co.at/2014/09/artemis-fowl-and-large-cardinals_22.html\nhttp://isomorphism.es/post/10782081422/what-comes-after-infinity-transfinite-arithmetic-and-ord\nhttps://lukepalmer.wordpress.com/2007/06/14/the-lesser-of-infinitely-many-evils/\n\nMUSIC BY:\nhttp://www.youtube.com/JakeChudnow\nhttp://www.audionetwork.com",
      "viewcount": 7916645,
      "author": "Vsauce",
      "url": "https://www.youtube.com/watch?v=SrU9YDoXE88",
      "title": "How To Count Past Infinity",
      "dislikes": 5805,
      "bigthumb": "https://i.ytimg.com/vi/SrU9YDoXE88/sddefault.jpg",
      "videoid": "SrU9YDoXE88",
      "keywords": ["infinity", "Math", "Maths", "vsauce", "michael stevens", "aleph", "omega", "transfinite", "ordinals", "cardinals", "inaccessible", "large cardinals", "set theory", "biggest number", "largest number", "biggest infinity", "last number", "end of numberline", "types of number", "number", "axiom", "science", "theory", "cantor", "beyond", "bigger than infinity", "after infinity", "counting", "ordinal numbers", "learn", "stem", "college", "high school", "test prep", "exam", "hugh woodin", "woodin cardinal", "woodin", "vihart", "the fault in our stars"],
      "length": 1426,
      "likes": 212006,
      "duration": "00:23:46",
      "thumb": "http://i.ytimg.com/vi/SrU9YDoXE88/default.jpg"
  }, {
      "dates": [],
      "tags": ["Space Exploration","NASA"],
      "size": ["Solar Systems"],
      "time": ["Modern Revolution"],
      "teaches": ["New Horizons","Pluto","Spacecraft","Size of the Solar System"],
      "is": ["video"],
      "discipline": ["Astronomy"],
      "username": "Vox",
      "rating": 4.92920353982,
      "description": "A tiny spacecraft has been traveling 9 years for this moment \u2014 the day we finally get a close look at Pluto. Here's what you need to know about NASA's New Horizon's mission.\n\nLearn more: http://www.vox.com/2015/7/9/8921713/pluto-mission-new-horizons-nasa-flyby\n\nSubscribe to our channel! http://goo.gl/0bsAjO\n\nVox.com is a news website that helps you cut through the noise and understand what's really driving the events in the headlines. Check out http://www.vox.com to get up to speed on everything from Kurdistan to the Kim Kardashian app. \n\nCheck out our full video catalog: http://goo.gl/IZONyE\nFollow Vox on Twitter: http://goo.gl/XFrZ5H\nOr on Facebook: http://goo.gl/U2g06o",
      "viewcount": 431730,
      "author": "Vox",
      "url": "https://www.youtube.com/watch?v=Eo3EJYo2dX8",
      "title": "NASA's incredible mission to Pluto, explained",
      "dislikes": 88,
      "bigthumb": "https://i.ytimg.com/vi/Eo3EJYo2dX8/sddefault.jpg",
      "videoid": "Eo3EJYo2dX8",
      "keywords": ["vox", "news", "current events", "world", "cnn", "vice", "fox", "msnbc", "breakdown", "eli5", "NASA (Spacecraft Manufacturer)", "Pluto (Astronomical Discovery)", "Astronomy (Field Of Study)", "space", "new horizons", "New Horizons (Space Mission)", "dwarf planet", "charon", "solar system", "Spacecraft (Industry)", "Space Exploration (Literature Subject)", "launch"],
      "length": 227,
      "likes": 4884,
      "duration": "00:03:47",
      "thumb": "http://i.ytimg.com/vi/Eo3EJYo2dX8/default.jpg"
  }, {
      "dates": ["1849","200 BC"],
      "tags": ["Adam Savage","Richard Feynman","Eratosthenes"],
      "size": ["Organism","Planetary Bodies"],
      "time": ["Collective Learning"],
      "teaches": ["Scientific Method","Speed of Light","Inertia","Size of the Earth","Science"],
      "is": ["video","history","evidence","experiment"],
      "discipline": ["Geography","Philosophy"],
      "username": "TED-Ed",
      "rating": 4.96780933494,
      "description": "Adam Savage walks through two spectacular examples of profound scientific discoveries that came from simple, creative methods anyone could have followed -- Eratosthenes' calculation of the Earth's circumference around 200 BC and Hippolyte Fizeau's measurement of the speed of light in 1849.",
      "viewcount": 2203078,
      "author": "TED-Ed",
      "url": "https://www.youtube.com/watch?v=F8UFGu2M2gM",
      "title": "How simple ideas lead to scientific discoveries",
      "dislikes": 227,
      "bigthumb": "https://i.ytimg.com/vi/F8UFGu2M2gM/sddefault.jpg",
      "videoid": "F8UFGu2M2gM",
      "keywords": ["Science and Technology", "Nature of Scientific Invention", "Adam Savage", "Inventions That Shaped History", "Science", "Technology", "Scientific Method", "Speed of Light", "Circumference of the Earth", "Inertia", "Physics", "Invention", "Scientific Discoveries", "Math", "TED", "TED-Ed", "TED Education", "TED-Ed Animation", "Jeremiah Dickey", "Celeste Lai", "Kari Mulholland", "Franz Palomares"],
      "length": 452,
      "likes": 28011,
      "duration": "00:07:32",
      "thumb": "http://i.ytimg.com/vi/F8UFGu2M2gM/default.jpg"
  }, {
      "dates": [],
      "tags": ["Astrology","ptolemy", "copernicus"],
      "size": ["Planetary Bodies","Solar Systems"],
      "time": [],
      "teaches": ["Retrograde Motion","geocentric","heliocentric"],
      "is": ["video"],
      "discipline": ["Astronomy"],
      "username": "Vox",
      "rating": 4.94953596288,
      "description": "The science buried under the pseudoscience.\n\n\nSubscribe to our channel! http://goo.gl/0bsAjO\n\nSources:\nMars photography by Tun\u00e7 Tezel: http://www.twanight.org/newtwan/galleries.asp?Sort=Photographer&Value=Tunc%20Tezel&page=1\nMars visualization from Nooch 86: https://www.youtube.com/watch?v=TK9ozJYELR8\nSolar system orbits via Michael Van Daniker, Andrew Lund, and the Astronomy Workshop of Douglas Hamilton at U. Maryland http://janus.astro.umd.edu/SolarSystems/\nPtolemaic system vsualizer via Nebraka Astronomy Applet Project: http://astro.unl.edu/naap/ssm/animations/ptolemaic.html\nRetrograde motion visualizer via MHeducation: http://highered.mheducation.com/olcweb/cgi/pluginpop.cgi?it=swf::800::600::/sites/dl/free/0072482621/78780/Retro_Nav.swf::Retrograde%20Motion\n\n\n\n\nVox.com is a news website that helps you cut through the noise and understand what's really driving the events in the headlines. Check out http://www.vox.com to get up to speed on everything from Kurdistan to the Kim Kardashian app. \n\nCheck out our full video catalog: http://goo.gl/IZONyE\nFollow Vox on Twitter: http://goo.gl/XFrZ5H\nOr on Facebook: http://goo.gl/U2g06o",
      "viewcount": 400405,
      "author": "Vox",
      "url": "https://www.youtube.com/watch?v=FtV0PV9MF88",
      "title": "Mercury retrograde, explained without astrology",
      "dislikes": 174,
      "bigthumb": "https://i.ytimg.com/vi/FtV0PV9MF88/sddefault.jpg",
      "videoid": "FtV0PV9MF88",
      "keywords": ["mercury retrograde", "astrology", "Astronomy", "retrograde motion", "explained", "space", "solar system", "geocentric", "heliocentric", "ptolemy", "copernicus", "illusion", "optical illusion", "orbit", "Earth", "mercury", "mars retrograde", "horoscopes", "science", "vox", "mercury in retrograde", "flat earth"],
      "length": 230,
      "likes": 13618,
      "duration": "00:03:50",
      "thumb": "http://i.ytimg.com/vi/FtV0PV9MF88/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Fundamental Particles and Forces"],
      "time": [],
      "teaches": ["Light","Electromagnetic Spectrum","Photon","wave-particle duality","Speed of Light","Visible Light"],
      "is": ["video"],
      "discipline": ["Physics","Quantum Mechanics"],
      "username": "Kurzgesagt \u2013 In a Nutshell",
      "rating": 4.96466864746,
      "description": "We are so used to some things that we stopped wondering about them. Like light. What is light? Some kind of wavy thing, right? Kind of. \n\nShort bonus video for the people waiting for new stuff. \n\nMusic by: \n\nhttps://soundcloud.com/epicmountain/light\nhttps://epicmountainmusic.bandcamp.com/track/light\nwww.epic-mountain.com\n\nOur Patreon: https://www.patreon.com/Kurzgesagt?ty=h\n\nVisit us on reddit/facebook/twitter. You know. Social media stuff.\n\nhttps://www.reddit.com/r/kurzgesagt\nhttp://kurzgesagt.org\nhttps://www.facebook.com/Kurzgesagt\nhttps://twitter.com/Kurz_Gesagt\n\nTHANKS A LOT TO OUR LOVELY PATRONS FOR SUPPORTING US:\n\nPhiroze Dalal, T0T0S, Ryan OHoro, Kay Brinkmann, A La Mode, Marcelo Fernandes de Souza Filho, Vince, Thomas Shiels, Tom Wardrop, Shawn Marincas, Pontus Att\u00e5sen, Paul, Horacio Medina, Jim Yang, Arnav Guleria, Clemens, Robert McKone, Tahseen Mushtaque, Todd Binkley, Jochen, Vahur S, Matthew von der Ahe, Thomas Russell, Erick, Vivek Kotecha, Nils Caspar, Holger Fassel, Artur Szczypta, Jeff Fellows, Daniel Duffee, Konstantin Shabashov, Jackson R Hanna, Tim drake, Pascal de Reuck, Mike Galles, ByeongWook Lee, Guus Ketelings, Franko Papi\u0107, Thalia, Narat Suchartsunthorn, Lorenz Zahn, Brian Aparicio, J\u00f6rg Vogelsang, Rashed Ali, Darwin Ranzone, Tyler Thornton, Bernat Unanue, David Pfister, Ash Patel, Han Saini, Ute Moll, Vrm Vee Are Em, Ioanna Bischinioti, Jenny Zhou, Vince Babbra, Dan Cortes, Matt K\n\nWhat is light?\n\nHelp us caption & translate this video!\n\nhttp://www.youtube.com/timedtext_cs_panel?c=UCsXVk37bltHxD1rDPwtNM8Q&tab=2",
      "viewcount": 2731775,
      "author": "Kurzgesagt \u2013 In a Nutshell",
      "url": "https://www.youtube.com/watch?v=IXxZRZxafEQ",
      "title": "What Is Light?",
      "dislikes": 547,
      "bigthumb": "https://i.ytimg.com/vi/IXxZRZxafEQ/sddefault.jpg",
      "videoid": "IXxZRZxafEQ",
      "keywords": ["light", "Physics", "photon", "wave", "visible light", "universe", "sun", "star", "speed of light", "particle", "energy", "funny", "earth", "magnet", "electromagnetism", "electron", "magnet field", "electric field", "science", "lights", "infographic", "kurzgesagt", "in a nutshell"],
      "length": 279,
      "likes": 61381,
      "duration": "00:04:39",
      "thumb": "http://i.ytimg.com/vi/IXxZRZxafEQ/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["The Universe","Observable Universe","Superclusters"],
      "time": [],
      "teaches": ["Dark Matter","Dark Energy","Expansion of Space","Matter","Accelerating Expansion of the Universe","Space","Gravity"],
      "is": ["video"],
      "discipline": ["Physics","Theoretical Physics"],
      "username": "Kurzgesagt \u2013 In a Nutshell",
      "rating": 4.97089447726,
      "description": "What is dark energy? What is dark matter? Well, if we knew exactly we would have a nobel prize \u2013 we know that they exist though. So what do we know about those strange things?\n\nCheck out THE NOVA PROJECT to learn more about dark energy: www.nova.org.au \n\nMusic by: www.epic-mountain.com\n\nVisit us on our Website, Twitter, Facebook, Patreon or Behance to say hi!\n\nhttp://kurzgesagt.org\nhttps://www.facebook.com/Kurzgesagt\nhttps://twitter.com/Kurz_Gesagt\nhttp://www.patreon.com/Kurzgesagt\nhttp://www.behance.net/Kurzgesagt\n\nTHANKS A LOT TO OUR LOVELY PATRONS FOR SUPPORTING US:\n\nAjay Shekhar, Charles Kelsey, Daniel P, Enrico, Eduardo Rampelotto Gatto, Philip, Andrew Cochran, Mahmut Kaynar, Jon Moroney, Charles Kuang, Eugene Cham, Brandon Helvie, David Garcia Quintas, Renaud Savignard, Yuki Reid, James, Maximilian Ritter, Loren Barcus, Viktor Asklund, Georg Faber, Bruno Deschatelets, Pablo Zetina, Massimiliano Cacciotti, Pranab Shenoy, Ignacio Flores, Yousif, Tom Langford, Luca Friedrich, Roy Ston, Jesse Powell, Dave, Philipi Adolfo Willemann, Koen Driessen, Terry Lipstein, Mike Horner, Peter Dexter, William Iverson, Wouter ten Bosch, Samuel Morissette, Tim Carll, Tersol, Dennis van Ruijven, Eugene schula, Wilker, \u51a0\u744b \u9673, Mason Y, Wei Wong, Hata'ab, Artem Anchugov, Anton Sterenborg, Nikki Toss, Jan Berdel, Torin Rettig, Jon Davis, ryandelsol, Sieglinde Geisel, Pierre Lacasse, Danylo Bozhagora, Jens-Ejnar Stephansen, Erven, Philly Cashion, varinder singh bal, Jerome Dimaano, Clayton Fussell, Daniel Ahlstr\u00f6m, Dan Q, Andres Jacobsen, Mikkel Jespersen, Igor Benicio de Mesquita, Don Smith, Dave Hng, Weston, Samuel Pacheco, Bear, Nate Rice, Victor C., Yeonghoon Park, Stephen Morris, Paul Strauss, Martin Fink-Jensen, Josh Allen, Eric, Karl Snickars, Greeny Liu, Marc Dumont, Jennifer Hiller, Tibor Schiemann, Michael Koldsgaard, Gilberto, Christian Fernandez, dante harper, John, B\u00fcnyamin Tetik, Ernst, Matthew Sample, Elchus, Hugo, Stefan Ghizelea, David, Lightbow, Simon Thibodeau, Stephen Morse, Amdrew, Nicolas Huguet-Latour, Peter \u0160iru\u010dek, Evan Low, Mehmet Sevil, Markus Wolski, Philip Freeman, Chris Thompson, Jesse MacLean, Soares, Harry, Dario W\u00fcnsch, Matt Collins, Yannick, Geoffrey Lee, Daniel McCouid-Carr, Doc Matthews, Dan Treasure, Romi Kuntsman, Laurence Dixon, Aurelien Gouny, Russell McCallion, Patrick Noble, Ziggy Freed, M4tc4t, ThereIsNoYeti, Erika Marks, Samuel Matchain, BurmansHealthShop, Cory Wright, Per Markus Edvardsen, Thomas Wagteveld, Brian David Henderson, THEGURUDK, Magnus Erichsen, Theo Alves Monteiro, Brett Cowie, Valentin, Sergio Uribe, Alejandro Medrano Gil, Tony Montuori, Praveen, Jeff, Malthe Agger, Harrison Leake, Robert Varasciuc, Bahjat, Spencer Clark, Joshua Grose, Eugene Foss, Mike Mintz, Colin Palin, James Khoo, Daniel OCL, Ben Nunan, Jay Kidd, Denis Smajlovic, Sofian Madi, Steffen Weng, CoVis CoWorking, Hamad, Pongskorn, Chris Smith, Jan E, Vojt\u011bch S\u00e1zel, Lethargicpanda, Gabriel Tougas, David Torres ,Mark Scheurwater, Andrew Connor, Lars Vas Dias, Peter Ficinus, Zahan Malkani, Collin Banko, Jacob Schirm, Erik Brizzee, Robby Olivam, Vaelohs, Applied Science, Alex Thaler, Nathanael, S\u00e9bastien Blanchet, Howard Lince III, William Parker, Steven, Lance White, Allan Farrell, Eli Fisker, Osric Lord-Williams, Alexander Kosenkov, Ryan A. Schauer, A Patron, Colman Joeri, Oren Milman, Maggie Chok, Emil, Diego Nakama, Rainbow Bleh, Lennart Rosam, Andrej Gukov, Adam Kenningham-Brown, James Spellman, John Gietzen, Chris Anderson, Joe Uong, \u00deorsteinn S\u00e6var Hjartarson, Richard Harrison, Paul Nel, Nick Yonge, Benoit Pette, Levi, Gustavo, Alexander Brazie, Albert Z, Dany, charlie, Evgenia Yigitalieva, Casey Mazzarella, Dave Neu, Scott Laing, Zr4g0n, Dimitry Ivanov, Doug Wollison, JAMES RUDNET, Gizem G\u00fcrkan, Lotean Loris, Brian Butler, George Chearswat, somersault18:24, Alto Ono, Ben Shackman, Matthew Gill, Reinaldo Mizutani, Jackson Tan, Julius Hofman, Demian Rosenblatt, Muath, Lucas Lohr, Edgar Duarte Ortega, Marvin, Javier de la Garza, Avi Yashchin , Peter \u017dnuderl, Stephen Chen, Bruno Ara\u00fajo, Alipasha Sadri, Jeff Churchill, Fernando Henrique, Timothy Noble, Carlos Garc\u00eda Rojas, Matthew Willhite, Daniel, Roman Doboni, Jose Caetano, Kevin P, Seona Tea, Carlos Bohorquez, Steven Ratner, Alexander, JiaJunQiu, Rob PT, Kymate, Bruce low, Jos\u00e9, Morten Myrland, Alessandro Frau, Brad Wardell, Simon Younan, Thomas Lee, David Harbinson, Danilo Caires, Alexander Scheffer, Finn Edwards, Rikard Nyberg, Nicholas Holtz, Adriano Collalti, Josh Yates-Walker, Jason Berlin, Bret Brizzee, Dylan, Florian Guitton, Andreas Kollmann, Steven Byrd, Jezariael Demos, Eric Austin\n\nHelp us caption & translate this video!\n\nhttp://www.youtube.com/timedtext_cs_panel?c=UCsXVk37bltHxD1rDPwtNM8Q&tab=2",
      "viewcount": 2796062,
      "author": "Kurzgesagt \u2013 In a Nutshell",
      "url": "https://www.youtube.com/watch?v=QAa2O_8wBUQ",
      "title": "What is Dark Matter and Dark Energy?",
      "dislikes": 478,
      "bigthumb": "https://i.ytimg.com/vi/QAa2O_8wBUQ/sddefault.jpg",
      "videoid": "QAa2O_8wBUQ",
      "keywords": ["Dark Energy", "Dark Matter", "Energy (Industry)", "Condensed Matter Physics (Field Of Study)"],
      "length": 381,
      "likes": 65214,
      "duration": "00:06:21",
      "thumb": "http://i.ytimg.com/vi/QAa2O_8wBUQ/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Organisms","Species"],
      "time": ["Collective Learning"],
      "teaches": ["Language","English","Word Origins"],
      "is": ["video","history"],
      "discipline": ["Sociology"],
      "username": "ouLearn on YouTube",
      "rating": 4.94274094636,
      "description": "TELL US WHAT YOU THINK and help us improve our Free Educational Resources\n\nhttps://www.surveymonkey.com/r/2015_YouTube_descr\n\nFor more like this subscribe to the Open University channel https://www.youtube.com/channel/UCXsH4hSV_kEdAOsupMMm4Qw\n\n\nFree learning from The Open University http://www.open.ac.uk/openlearn/history-the-arts/culture/english-language\n\n---\n\nA look at the history of the English language. (this is a combination of all 10 parts of the series into one video)\n\n(all parts - combined)\nPlaylist link - http://www.youtube.com/playlist?list=PLA03075BAD88B909E\n\n---\n\nStudy 'English Language' at the Open University: http://www3.open.ac.uk/study/undergraduate/languages/english-language/index.htm \n\nExplore qualifications in Languages with the OU\nhttp://www3.open.ac.uk/study/undergraduate/languages/index.htm\n\nExplore qualifications in Arts and Humanities with the OU http://www3.open.ac.uk/study/undergraduate/arts-and-humanities/index.htm\n\nStudy 'Worlds of English' with the OU http://www3.open.ac.uk/study/undergraduate/course/u214.htm\n\n---",
      "viewcount": 1559830,
      "author": "ouLearn on YouTube",
      "url": "https://www.youtube.com/watch?v=H3r9bOkYW9s",
      "title": "History of English (combined)",
      "dislikes": 222,
      "bigthumb": "https://i.ytimg.com/vi/H3r9bOkYW9s/sddefault.jpg",
      "videoid": "H3r9bOkYW9s",
      "keywords": ["History", "of", "English", "combined"],
      "length": 681,
      "likes": 15269,
      "duration": "00:11:21",
      "thumb": "http://i.ytimg.com/vi/H3r9bOkYW9s/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Planetary Body","Interstellar Neighborhoods"],
      "time": ["The Future"],
      "teaches": ["Star","Red Dwarf","Brown Dwarfs","Habitable Zone","Blue Dwarf","White Dwarf","Stellar Evolution","Black Dwarf","End of the Universe","Heat death of the universe"],
      "is": ["video","end"],
      "discipline": ["Cosmology","Astronomy"],
      "username": "Kurzgesagt \u2013 In a Nutshell",
      "rating": 4.954164505,
      "description": "The last star in the universe will be a red dwarf. Red dwarfs in general might be great places to look for aliens \u2013 or planets for humans to find a new home after our solar system has died.\n\nSupport us on Patreon so we can make more stuff (and get cool wallpapers): https://www.patreon.com/Kurzgesagt?ty=h\n\nGet the music of the video here: \n\nhttps://epicmountainmusic.bandcamp.com/track/red-dwarfs\n\nhttps://soundcloud.com/epicmountain/red-dwarfs\n\nhttp://epic-mountain.com\n\nOr follow us on social media or reddit: \n\nhttp://kurzgesagt.org\nhttps://www.reddit.com/r/kurzgesagt\nhttps://twitter.com/Kurz_Gesagt\nhttps://www.facebook.com/Kurzgesagt\n\nTHANKS A LOT TO OUR LOVELY PATRONS FOR SUPPORTING US:\n\n(This video has been uploaded on the road, Patrons will be added on Monday!!)\n\nThe Last Star in the Universe \u2013 Red Dwarfs Explained\n\nHelp us caption & translate this video!\n\nhttp://www.youtube.com/timedtext_cs_panel?c=UCsXVk37bltHxD1rDPwtNM8Q&tab=2",
      "viewcount": 4361777,
      "author": "Kurzgesagt \u2013 In a Nutshell",
      "url": "https://www.youtube.com/watch?v=LS-VPyLaJFM",
      "title": "The Last Star in the Universe \u2013 Red Dwarfs Explained",
      "dislikes": 1067,
      "bigthumb": "https://i.ytimg.com/vi/LS-VPyLaJFM/sddefault.jpg",
      "videoid": "LS-VPyLaJFM",
      "keywords": ["red dwarf", "universe", "heat death", "end of the universe", "death", "space", "sun", "star", "Physics", "Astronomy", "life cycle", "hydrogen", "helium", "humans", "earth", "aliens", "alien life", "exoplanet", "gas giant", "super earth", "white dwarf", "black dwarf", "life", "last star", "funny", "kurzgesagt", "in a nutshell", "future"],
      "length": 350,
      "likes": 92049,
      "duration": "00:05:50",
      "thumb": "http://i.ytimg.com/vi/LS-VPyLaJFM/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Atoms"],
      "time": [],
      "teaches": ["Periodic Table","Quantum Numbers","Orbitals"],
      "is": ["video"],
      "discipline": [],
      "username": "cassiopeiaproject",
      "rating": 4.66666650772,
      "description": "Find out more about the Periodic Table!",
      "viewcount": 123810,
      "author": "cassiopeiaproject",
      "url": "https://www.youtube.com/watch?v=5MMWpeJ5dn4",
      "title": "Periodic Table",
      "dislikes": 25,
      "bigthumb": "",
      "videoid": "5MMWpeJ5dn4",
      "keywords": ["Chemistry", "Periodic", "Table", "atom", "electron", "element", "quantum", "number", "orbital", "energy"],
      "length": 230,
      "likes": 275,
      "duration": "00:03:50",
      "thumb": "http://i.ytimg.com/vi/5MMWpeJ5dn4/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Fundamental Particles and Forces","subatomic Particles"],
      "time": ["Modern Revolution"],
      "teaches": ["LHC","Compact Muon Solenoid (CMS)","particle accelerators","ALICE","ATLAS","LHCb","standard model"],
      "is": ["video","experiment"],
      "discipline": ["Physics","Quantum Mechanics"],
      "username": "Fermilab",
      "rating": 4.9588688946,
      "description": "The Large Hadron Collider or LHC is the world\u2019s biggest particle accelerator, but it can only get particles moving very quickly.  To make measurements, scientists must employ particle detectors. There are four big detectors at the LHC: ALICE, ATLAS, CMS, and LHCb.  In this video, Fermilab\u2019s Dr. Don Lincoln introduces us to these detectors and gives us an idea of each one\u2019s capabilities.\n\nRelated videos:\nhttp://www.youtube.com/watch?v=debQ60QVtYQ\nhttp://www.youtube.com/watch?v=-d6sKfPfYTU",
      "viewcount": 12438,
      "author": "Fermilab",
      "url": "https://www.youtube.com/watch?v=X3tvgyrb2X4",
      "title": "The LHC Experiments",
      "dislikes": 4,
      "bigthumb": "https://i.ytimg.com/vi/X3tvgyrb2X4/sddefault.jpg",
      "videoid": "X3tvgyrb2X4",
      "keywords": ["physicist", "proof", "CMS", "metaphor", "scientist", "Large Hadron Collider", "Compact Muon Solenoid", "example", "Ian Krass", "A Large Ion Collider Experiment", "learn", "Don Lincoln", "educational", "ALICE", "CERN", "particle", "LHC", "LHCb", "particle detectors", "Physics", "discovery", "A Toroidal LHC ApparatuS", "explained", "ATLAS", "funny", "Fermilab", "Physics", "science", "foam finger", "higgs", "boson", "accelerator", "detector", "camera", "huge", "collisions", "experiment", "collide", "amazing", "technology", "matter", "quark", "gluon", "plasma", "atoms", "subatomic", "big bang", "universe", "machines"],
      "length": 415,
      "likes": 385,
      "duration": "00:06:55",
      "thumb": "http://i.ytimg.com/vi/X3tvgyrb2X4/default.jpg"
  }, {
      "dates": [],
      "tags": [],
      "size": ["Fundamental Particles and Forces","subatomic Particles"],
      "time": ["Modern Revolution"],
      "teaches": ["supersymmetry","standard model","forces","matter"],
      "is": ["video","theory"],
      "discipline": ["Physics","Quantum Mechanics","Mathematics","Theoretical Physics"],
      "username": "Fermilab",
      "rating": 4.86897313213,
      "description": "In this video, Fermilab's Dr. Don Lincoln describes the principle of supersymmetry in an easy-to-understand way.  A theory is supersymmetric if it treats forces and matter on an equal footing.  While supersymmetry is an unproven idea, it is popular with particle Physics researchers as a possible next step in particle Physics.",
      "viewcount": 230465,
      "author": "Fermilab",
      "url": "https://www.youtube.com/watch?v=0CeLRrBAI60",
      "title": "What is Supersymmetry?",
      "dislikes": 89,
      "bigthumb": "https://i.ytimg.com/vi/0CeLRrBAI60/sddefault.jpg",
      "videoid": "0CeLRrBAI60",
      "keywords": ["Fermilab", "Physics", "Supersymmetry", "SUSY", "supersymmetric", "standard model", "particles", "matter", "energy", "space", "time", "particle", "questions", "theories", "force", "mysteries", "misconception", "principle", "charity", "symmetry", "sphere", "Math", "equation", "fermions", "bosons", "explained", "proof", "metaphor", "example", "scientist", "science", "physicist", "don lincoln", "universe", "cousin", "research", "ian krass", "simple", "graphics", "Mathematics", "theory", "reason", "fun", "teaching", "learn", "educational", "funny", "higgs boson", "higgs", "dark matter", "weak gravity", "discovery", "explanation"],
      "length": 344,
      "likes": 2628,
      "duration": "00:05:44",
      "thumb": "http://i.ytimg.com/vi/0CeLRrBAI60/default.jpg"
  }, {
      "dates": [],
      "tags": ["panda","rhino","triage"],
      "size": ["species","biological community"],
      "time": ["Modern Revolution"],
      "teaches": ["extinction","conservation","sustainability","ecosystem","endangered species"],
      "is": ["video"],
      "discipline": ["Ecology"],
      "username": "MinuteEarth",
      "rating": 4.90554615529,
      "description": "Thanks to http://www.harrys.com for supporting this video. Use the coupon code MINUTEEARTH for $5 off your order! http://www.harrys.com \nHelp fund MinuteEarth on Patreon: https://goo.gl/ZVgLQZ\n\nThanks to our Patreon patrons:\n- @AntoineCoeur\n- Nicholas Buckendorf\n- Nasser Hamed Alminji\n- Jeff Straathof\n- Mark\n- facebook.com/maarten.bremer\n- Emil Kampp\n- @TodayIFoundOut1\n\nThanks also to our Subbable supporters:\n- @Kubakun :-)\n- Ethi Raj\n- Damian Shaw\n- Ernesto Carvajal - https://www.facebook.com/erne.carvajal\n- Shelley Jones - https://twitter.com/ShelleytheJonas\n- Vanessa Benavent\n- BouwsT\n- Zoe Reidinger\n- @prosystrangers\n- Pigmy Wurm\n- John Harman (from Dayton, OH)! - http://www.youtube.com/watch?v=0fKBhvDjuy0#at=29\n- @WY_Tang\n___________________________________________\n\nMinuteEarth provides an energetic and entertaining view of trends in earth\u2019s environment \u2013 in just a few minutes!\n\nCreated by Henry Reich\n\nWith the MinuteEarth team: Alex Reich, Peter Reich, Emily Elert, Ever Salazar, Kate Yoshida, and Henry Reich. Music by Nathaniel Schroeder: http://www.soundcloud.com/drschroeder\n________________________\n\nPlease support us on Patreon: https://www.patreon.com/minuteearth\n\nAnd follow us on Vessel: https://www.vessel.com/shows/6891774506155638\n\nAnd YouTube: http://www.youtube.com/user/minuteearth?sub_confirmation=1\n\nAnd ...  iTunes: https://goo.gl/sfwS6n\n\nFacebook: http://facebook.com/minuteearth\n\nTwitter: http://twitter.com/MinuteEarth\n________________________\n\nWant to learn more about the topic in this week\u2019s video? Here are some key words/phrases to get your googling started:\n\n- keystone species \u2013 a species that plays a crucial role in the functioning of an ecosystem\n- flagship species \u2013 species used as an icon for an environmental cause\n- threatened species - species assessed by the IUCN as critically endangered, endangered, or vulnerable\n- triage - assigning degrees of urgency to a large number of patients to determine the order of treatment\n________________________\n\nReferences:\n\nIUCN 2014. The IUCN Red List of Threatened Species. Version 2014.3. http://www.iucnredlist.org/\n\nJoseph, L. N., Maloney R. F., & Possingham, H. P. (2009) Optimal allocation of resources among threatened species: a project prioritization protocol. Conservation Biology 23:328-338. http://www.uq.edu.au/spatialecology/docs/Publications/2009_Joseph_etal_OptimalAllocation.pdf\n\nSmall, E. (2011) The new Noah\u2019s Ark: beautiful and useful species only. Part 1. Biodiversity conservation issues and priorities. Biodiversity 12(4): 232 - 247. http://www.tandfonline.com/doi/abs/10.1080/14888386.2011.642663#\n\nSmith, R.J., Verissimo, D.; Isaac, N.J.B., & Jones, K.E. (2012) Identifying Cinderella species: uncovering mammals with conservation flagship appeal. Conservation Letters, 5 (3): 205 - 212. http://onlinelibrary.wiley.com/doi/10.1111/j.1755-263X.2012.00229.x/abstract\n\nSitas, N., Baillie, J.E.M., and Isaac, N.J.B. (2009) What are we saving? Developing a standardized approach for conservation action. Animal Conservation, 12(3): 231- 237. http://onlinelibrary.wiley.com/doi/10.1111/j.1469-1795.2009.00244.x/full\n\nUS Fish and Wildlife Service. (1999) South Florida Multi-Species Recovery Plan. Mangroves: 3-519 - 3-552. http://www.fws.gov/verobeach/msrppdfs/mangroves.pdf\n\nWarren, L. (June 2006) Panda, Inc. National Geographic Magazine. http://ngm.nationalgeographic.com/2006/07/panda/warren-text\n\nWorld Wildlife Fund. (2014) Annual Report. http://assets.worldwildlife.org/financial_reports/21/reports/original/2014_Annual_Report.pdf?1418325091&_ga=1.146888247.1239564205.1427657892\n________________________\n\nImage Credits:\n\nStinking Cedar (Torreya taxifolia) - Jerry A. Payne - http://bit.ly/1EyduHa\n\nPygmy hog-sucking Louse (Haematopinus oliveri) - Zoological Survey of India - http://bit.ly/1JdxxvD\n\nSturgeon - Wikimedia user Cacophony - http://bit.ly/1DOjpFA\n\nSaiga Anthelope - Wikimedia user Seilov - http://bit.ly/1E0O0Pq\n\nEchinocactus grusonii - Andr\u00e9 Karwath - http://bit.ly/1IucNBw\n\nCork Oak (Quercus suber) - Wikimedia user Joergsam - http://bit.ly/1ziQOLU\n\nHumphead wrasse (Cheilinus undulatus) - Patryk Krzyzak - http://bit.ly/1GLUf0g\n\nPaddlefish - U.S. Fish and Wildlife Service Headquarters - http://bit.ly/1GLUdFX\n\nSwietenia macrophylla - Flickr User jayeshpatil912 - http://bit.ly/1HWzhuB\n\nArakan forest turtle - Public Domain - http://bit.ly/1dzlAqh\n\nPurple Frog - Wikimedia User Karthickbala - http://bit.ly/1JF1Hv8\n\nCute Panda - Wikimedia User Sheilalau (Public Domain) - http://bit.ly/1c0JURt\n\nFrohawk Dodo - Frederick William Frohawk (Public Domain) - http://bit.ly/1bInEer",
      "viewcount": 1228393,
      "author": "MinuteEarth",
      "url": "https://www.youtube.com/watch?v=VEMtc1w4z6c",
      "title": "Should We Let Pandas Go Extinct?",
      "dislikes": 628,
      "bigthumb": "https://i.ytimg.com/vi/VEMtc1w4z6c/sddefault.jpg",
      "videoid": "VEMtc1w4z6c",
      "keywords": ["MinuteEarth", "Minute Earth", "MinutePhysics", "Minute Physics", "earth", "history", "science", "environment", "environmental science", "earth science", "conservation", "species", "triage", "policy", "biology", "endangered species", "pandas", "extinction", "threatened", "biodiversity", "wildlife", "rhinos", "otters", "mangroves", "economics", "ecosystems", "pygmy hog-sucking louse", "stinking cedar", "Giant Panda (Animal)", "World Wide Fund For Nature (Nonprofit Organization)"],
      "length": 188,
      "likes": 25967,
      "duration": "00:03:08",
      "thumb": "http://i.ytimg.com/vi/VEMtc1w4z6c/default.jpg"
  },
]
